### PR TITLE
❇️ min gui and backend

### PR DESCRIPTION
**Pull request by xgdgsc**
#2 , might add yaml parsing later. gui seems to work.

### CODE REVIEW

**Comment by sigmaSd** [comment]
Thanks for working on this!

These new elements make the window unusable on small screens, for now I think  you use a scroll window to make it at least scrollable
```diff
diff --git a/crates/gui/src/gui.rs b/crates/gui/src/gui.rs
index 5253f6a..6527eea 100644
--- a/crates/gui/src/gui.rs
+++ b/crates/gui/src/gui.rs
@@ -61,7 +61,7 @@ fn build_ui(application: &gtk::Application) {
     window.set_title("ElTrafico");
     window.set_border_width(10);
     window.set_position(gtk::WindowPosition::Center);
-    window.set_default_size(300, 500);
+    window.set_default_size(800, 600);
 
     let main_box = Box::new(Orientation::Vertical, 10);
     let interface_row = create_interface_row(stdin.clone());
diff --git a/crates/gui/src/gui/widget_builder.rs b/crates/gui/src/gui/widget_builder.rs
index 1e7c77e..5e0e00d 100644
--- a/crates/gui/src/gui/widget_builder.rs
+++ b/crates/gui/src/gui/widget_builder.rs
@@ -23,7 +23,11 @@ fn get_unit(widget: &ComboBoxText) -> String {
     widget.active_text().unwrap().to_string()
 }
 
-pub fn create_row(name: Option<&str>, stdin: SharedStdinHandle, global: bool) -> Box {
+pub fn create_row(
+    name: Option<&str>,
+    stdin: SharedStdinHandle,
+    global: bool,
+) -> gtk::ScrolledWindow {
     //TODO switch to a gtk::grid
     let name = name.unwrap_or("?").to_string();
     let print_name = format!("<b>{}</b>", &name);
@@ -148,7 +152,10 @@ pub fn create_row(name: Option<&str>, stdin: SharedStdinHandle, global: bool) ->
     hbox.add(&Label::new(Some("Active:")));
     hbox.add(&set_btn);
 
-    hbox
+    let scrolled_box: ScrolledWindow = ScrolledWindow::new::<Adjustment, Adjustment>(None, None);
+    scrolled_box.add(&hbox);
+
+    scrolled_box
 }
 
 pub fn update_gui_program_speed(app_box: gtk::Box, programs_speed: HashMap<String, (f32, f32)>) {
@@ -173,7 +180,8 @@ pub fn update_gui_program_speed(app_box: gtk::Box, programs_speed: HashMap<Strin
     }
 }
 
-pub fn update_gui_global_speed(global_bar: gtk::Box, global_speed: (f32, f32)) {
+pub fn update_gui_global_speed(scrolled_box: gtk::ScrolledWindow, global_speed: (f32, f32)) {
+    let global_bar: gtk::Container = scrolled_box.child().unwrap().downcast().unwrap();
     let speed: gtk::Label = global_bar.children()[1].clone().downcast().unwrap();
     speed.set_label(&format!(
         "Down: {:.2} KB/sec Up: {:.2} KB/sec",
```

The ui definitely needs a rewrite its ux is very lacking, but that something I guess I should do down the line.

One other suggestion can we make this optional behind a flag for example `--with-min` , I don't see myself use the feature so I prefer if I don't have a cluttered ui for something I don't use.

**Comment by sigmaSd** [comment]
Or maybe behind an advanced tick box

**Comment by sigmaSd** [comment]
This is what I propose for now
```diff
diff --git a/crates/gui/src/gui.rs b/crates/gui/src/gui.rs
index 5253f6a..6527eea 100644
--- a/crates/gui/src/gui.rs
+++ b/crates/gui/src/gui.rs
@@ -61,7 +61,7 @@ fn build_ui(application: &gtk::Application) {
     window.set_title("ElTrafico");
     window.set_border_width(10);
     window.set_position(gtk::WindowPosition::Center);
-    window.set_default_size(300, 500);
+    window.set_default_size(800, 600);
 
     let main_box = Box::new(Orientation::Vertical, 10);
     let interface_row = create_interface_row(stdin.clone());
diff --git a/crates/gui/src/gui/widget_builder.rs b/crates/gui/src/gui/widget_builder.rs
index 1e7c77e..b534e7a 100644
--- a/crates/gui/src/gui/widget_builder.rs
+++ b/crates/gui/src/gui/widget_builder.rs
@@ -23,7 +23,9 @@ fn get_unit(widget: &ComboBoxText) -> String {
     widget.active_text().unwrap().to_string()
 }
 
-pub fn create_row(name: Option<&str>, stdin: SharedStdinHandle, global: bool) -> Box {
+pub fn create_row(name: Option<&str>, stdin: SharedStdinHandle, global: bool) -> gtk::Container {
+    let advanced = std::env::args().any(|s| &s == "--advanced");
+
     //TODO switch to a gtk::grid
     let name = name.unwrap_or("?").to_string();
     let print_name = format!("<b>{}</b>", &name);
@@ -139,16 +141,26 @@ pub fn create_row(name: Option<&str>, stdin: SharedStdinHandle, global: bool) ->
     hbox.add(&up);
     hbox.add(&up_value);
     hbox.add(&up_unit);
-    hbox.add(&down_min);
-    hbox.add(&down_min_value);
-    hbox.add(&down_min_unit);
-    hbox.add(&up_min);
-    hbox.add(&up_min_value);
-    hbox.add(&up_min_unit);
+
+    if advanced {
+        hbox.add(&down_min);
+        hbox.add(&down_min_value);
+        hbox.add(&down_min_unit);
+        hbox.add(&up_min);
+        hbox.add(&up_min_value);
+        hbox.add(&up_min_unit);
+    }
+
     hbox.add(&Label::new(Some("Active:")));
     hbox.add(&set_btn);
 
-    hbox
+    if advanced {
+        let scrolled_box = ScrolledWindow::new::<Adjustment, Adjustment>(None, None);
+        scrolled_box.add(&hbox);
+        scrolled_box.upcast()
+    } else {
+        hbox.upcast()
+    }
 }
 
 pub fn update_gui_program_speed(app_box: gtk::Box, programs_speed: HashMap<String, (f32, f32)>) {
@@ -173,7 +185,8 @@ pub fn update_gui_program_speed(app_box: gtk::Box, programs_speed: HashMap<Strin
     }
 }
 
-pub fn update_gui_global_speed(global_bar: gtk::Box, global_speed: (f32, f32)) {
+pub fn update_gui_global_speed(scrolled_box: gtk::Container, global_speed: (f32, f32)) {
+    let global_bar: gtk::Container = scrolled_box.children()[1].clone().downcast().unwrap();
     let speed: gtk::Label = global_bar.children()[1].clone().downcast().unwrap();
     speed.set_label(&format!(
         "Down: {:.2} KB/sec Up: {:.2} KB/sec",
```

**Comment by xgdgsc** [comment]
I merged your code and added title align and different default window size under `--advanced`.

**Comment by sigmaSd** [comment]
I add a commit that makes the bar a scrolled window by default because other wise the code gets more complex when down-casting we will need to branch. Also I updated the down-casting as needed.

Thanks a lot for your work on this!

**Pull request merged**
